# Generated by Django 2.1 on 2019-01-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_created=True, verbose_name='Дата'),
        ),
    ]
